#!/usr/bin/env sh

# Validate that the commit message follows the Conventional Commit format
if ! head -1 "$1" | grep -qE "^(\(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?:\)|Merge .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid. Please follow the Conventional Commit format." >&2
    exit 1
fi

# Check that the commit message is not too long (should not exceed 100 characters)
if ! head -1 "$1" | grep -qE "^.{1,100}$"; then
    echo "Aborting commit. Your commit message is too long. It should not exceed 100 characters." >&2
    exit 1
fi
